services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=America/Sao_Paulo
    volumes:
      - /srv/plex/config:/config
      - /srv/plex/transcode:/transcode
      - /srv/media/Plex/Videos:/data/Videos
      - /srv/media/Plex/Filmes:/data/Filmes
    restart: unless-stopped

