networks:
  media-center:
    driver: bridge

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    networks:
      - media-center
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    restart: unless-stopped
  
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - URL=${LAB_URL}
      - VALIDATION=${VALIDATION}
      - DNSPLUGIN=${DNSPLUGIN}
    volumes:
      - /srv/swag:/config
    networks:
      - media-center
    #ports:
     # - 80:80
     # - 443:443
    restart: unless-stopped
  
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /srv/heimdall:/config
    networks:
      - media-center
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - media-center
    ports:
      #- "8082:8082"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /srv/media/downloads:/downloads
      - /srv/qbittorrent/config:/config
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - media-center
    #ports:
      #- "8083:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /srv/prowlarr/config:/config
    restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - media-center
    #ports:
      #- 8191:8191
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - media-center
    #ports:
      #- "8084:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /srv/radarr/config:/config
      - /srv/media/downloads:/downloads
      - /srv/media/center/Filmes:/movies
      - /srv/nfty-arr-script:/config/custom_scripts
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media-center
    #ports:
      #- "8085:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /srv/sonarr/config:/config
      - /srv/media/downloads:/downloads
      - /srv/media/center/Series:/tv
      - /srv/nfty-arr-script:/config/custom_scripts
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - media-center
    #ports:
      #- "8086:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /srv/bazarr/config:/config
      - /srv/media/center/Filmes:/movies
      - /srv/media/center/Series:/tv
    restart: unless-stopped

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    networks:
      - media-center
    ports:
      - "8087:7575"
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
      - TZ=America/Sao_Paulo
    volumes:
      - ./config:/app/data/configs
      - ./icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/homarr/appdata:/appdata
    restart: unless-stopped

  dash-dot:
    image:   mauricenino/dashdot:latest
    container_name: dash-dot
    networks:
      - media-center
    ports:
      - 8088:3001
    environment:
      - TZ=America/Sao_Paulo
      #- DASHDOT_ROUTING_PATH=${DASHDOT_WIDGET_URL}
    volumes:
      - /:/mnt/host:ro
    privileged: true
    restart: unless-stopped
  
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - media-center
    #ports:
      #- 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/media/center/Series:/data/tvshows
      - /srv/media/center/Filmes:/data/movies
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    networks:
      - media-center
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle/users.yml:/data/users.yml
    #ports:
      #- 8090:8080
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
      - DOZZLE_BASE=/dozzle
 
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8081:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    networks:
      - media-center
    volumes:
      - /srv/media:/srv
      - /srv/filebrowser/config:/config
      - /srv/filebrowser/database:/database
    command: [
      "--database", "/database/filebrowser.db",
      "--config", "/config/.filebrowser.json",
      "--root","/srv",
      "--address","0.0.0.0",
      "--baseurl","/filebrowser"
    ]
    restart: unless-stopped
  keepassxc:
    image: lscr.io/linuxserver/keepassxc:latest
    container_name: keepassxc
    networks:
      - media-center
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - CUSTOM_USER=${KP_USER}
      - PASSWORD=${KP_PW}
      - SUBFOLDER=${KP_PATH}
    volumes:
      - /srv/keepassxc:/config
      - /srv/media/backup:/data
    shm_size: "1gb"
    restart: unless-stopped
